os: linux

linux:
  - trusty

# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false


stages:
  - compile
    script: bash scripts/compile.sh
  - test
    script: bash scripts/test.sh
  - name: deploy-staging
    if: branch = staging
    script: bash -c echo "Deploying to staging s3"
		deploy:
			provider: script
			script: bash scripts/deploy.sh staging
			on:
				branch: staging
  - name: deploy-prod
    if: branch = production
    script: bash -c echo "Deploying to production s3"
		deploy:
			provider: script
			script: bash scripts/deploy.sh production
			on:
				branch: production
