---
os: linux

linux:
  - trusty

# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false


jobs:
  include:
    - stage: compile
      script: bash scripts/compile.sh

    - stage: test
      script: bash scripts/test.sh

    - stage: deploy-staging
      script: bash -c echo "Deploying to staging s3"
      deploy:
        provider: script
        script: bash scripts/deploy.sh staging

    - stage: deploy-prod
      script: bash -c echo "Deploying to production s3"
      deploy:
        provider: script
        script: bash scripts/deploy.sh production
